app:
  security:
    jwt: ''
  logs:
    url: 'http://localhost:9000/'
    token: 'admin'
spring:
  datasource:
    url: jdbc:h2:mem:lindsey
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  redis:
    host: 'localhost'
  rabbitmq:
    host: localhost
    password: guest
